/**
 * NOTE: This file is ignored from git tracking. In a CI environment it is
 * generated by firebase-ci based on config in .firebaserc (see .gitlab-ci.yaml).
 * This is done so that environment specific settings can be applied.
 */

export const env = 'dev'

// Config for firebase
export const firebase = {
  apiKey: 'AIzaSyBV9ZmFxmw2prYwq1gS49DAdQqPGNTN01I',
  authDomain: 'timecapture-75c8a.firebaseapp.com',
  databaseURL: 'https://timecapture-75c8a.firebaseio.com',
  projectId: 'timecapture-75c8a',
  storageBucket: 'timecapture-75c8a.appspot.com',
  messagingSenderId: '243709554550'
}

// Config to override default reduxFirebase config in store/createStore
// which is not environment specific.
// For more details, visit http://react-redux-firebase.com/docs/api/enhancer.html
export const reduxFirebase = {
  enableLogging: false, // enable/disable Firebase Database Logging
}

export const analyticsTrackingId = ''

export const publicVapidKey = 'BBBuUMEadLtl7j_mBgkMRjYuchthp95gZTb4KlBZRVXb5bsLFAqLZ-M8rPwTmLJglZwaUWxYjsCLnojuvbnc3KM' 

export const sentryDsn = ''

export default {
  env,
  firebase,
  reduxFirebase,
  publicVapidKey,
  analyticsTrackingId
}
